# Generated by Django 4.2.3 on 2023-07-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0002_scripts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Script',
        ),
    ]
