# Generated by Django 4.2.3 on 2023-07-07 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0003_delete_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
