# Generated by Django 4.2.2 on 2023-07-19 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0004_alter_scripts_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('choices', models.TextField()),
                ('correct_choice', models.CharField(max_length=1)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Learn.scripts')),
            ],
        ),
    ]
