# Generated by Django 4.2.2 on 2023-07-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0007_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
