# Generated by Django 4.2.2 on 2023-07-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0011_quizquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
