# Generated by Django 4.2.2 on 2023-07-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0017_quizquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
