# Generated by Django 4.2.2 on 2023-07-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0019_mcq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MCQ',
        ),
    ]
