# Generated by Django 4.2.2 on 2023-07-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0023_mcq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
