# Generated by Django 4.2.2 on 2023-07-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0024_alter_mcq_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MCQ',
        ),
    ]
