# Generated by Django 4.2.2 on 2023-07-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0028_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripts',
            name='episode_number',
            field=models.IntegerField(default=1),
        ),
    ]
