# Generated by Django 4.2.2 on 2023-07-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0029_scripts_episode_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripts',
            name='unique_identifier',
            field=models.CharField(default='', max_length=50),
        ),
    ]
