# Generated by Django 4.2.2 on 2023-07-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0032_scripts_episode_number_scripts_unique_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scripts',
            name='episode_number',
        ),
        migrations.RemoveField(
            model_name='scripts',
            name='unique_identifier',
        ),
    ]
