# Generated by Django 4.2.2 on 2023-07-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0033_remove_scripts_episode_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripts',
            name='episode_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
