# Generated by Django 4.2.2 on 2023-07-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0034_scripts_episode_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scripts',
            old_name='episode_number',
            new_name='episode',
        ),
    ]
