# Generated by Django 4.2.2 on 2023-07-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0035_rename_episode_number_scripts_episode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
