# Generated by Django 4.2.2 on 2023-07-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0036_delete_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('generated_script', models.TextField()),
                ('quiz', models.TextField()),
            ],
        ),
    ]
