# Generated by Django 4.2.2 on 2023-07-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0037_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
