# Generated by Django 4.2.2 on 2023-07-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0041_delete_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('generated_script', models.TextField()),
                ('questions', models.TextField()),
                ('choices', models.TextField()),
                ('correct_answers', models.TextField()),
            ],
        ),
    ]
