# Generated by Django 4.2.2 on 2023-07-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0043_rename_choices_quiz_quiz_remove_quiz_correct_answers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
