# Generated by Django 4.2.2 on 2023-07-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0047_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
