# Generated by Django 4.2.2 on 2023-07-31 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0049_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='script',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Learn.scripts'),
        ),
    ]
