# Generated by Django 4.2.2 on 2023-07-31 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0050_quiz_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='script',
        ),
    ]
