# Generated by Django 4.2.2 on 2023-07-31 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0051_remove_quiz_script'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
