# Generated by Django 4.2.2 on 2023-07-31 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0052_delete_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('generated_script', models.TextField()),
                ('quiz', models.TextField()),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Learn.scripts')),
            ],
        ),
    ]
