# Generated by Django 4.2.2 on 2023-08-01 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0054_remove_quiz_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='script',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Learn.scripts'),
        ),
    ]
