# Generated by Django 4.2.2 on 2023-08-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0055_quiz_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripts',
            name='quiz',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
